@startuml
set namespaceSeparator ::

class "ecommerce::Core::Provider::AppConfigProvider.dart::AppConfigProvider" {
  +String token
  +void updateToken()
}

"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Core::Provider::AppConfigProvider.dart::AppConfigProvider"

class "ecommerce::Core::Theme::MyTheme.dart::MyTheme" {
  {static} +Color darkBlue
  {static} +Color blue
  {static} +Color lightBlue
  {static} +Color backGround
  {static} +ThemeData darkTheme
}

"ecommerce::Core::Theme::MyTheme.dart::MyTheme" o-- "dart::ui::Color"
"ecommerce::Core::Theme::MyTheme.dart::MyTheme" o-- "flutter::src::material::theme_data.dart::ThemeData"

class "ecommerce::Core::Utils::Dialog_Utils.dart::MyDialogUtils" {
  {static} +dynamic showErrorDialog()
  {static} +dynamic showLoading()
  {static} +dynamic showSuccessDialog()
  {static} +dynamic hideDialog()
}

class "ecommerce::Data::Api::ApiManager.dart::ApiManager" {
  {static} -ApiManager? _instance
  +String baseUrl
  +String addUserRoute
  +String addUserImageRoute
  +String loginRoute
  +String getCategoriesRoute
  +String getAllNewAddedProductsRoute
  +String getProductsByCategoryRoute
  +String getProductDetailsRoute
  +String getSearchedProductsRoute
  +String getCartProductsRoute
  +String addProductToCartRoute
  +String deleteProductFromCartRoute
  +String addOrderRoute
  {static} +ApiManager getApiManager()
  +Future<CreateUserResponseDTO> addNewUser()
  +Future<String> uploadUserImage()
  +Future<LoginResponseDTO> login()
  +Future<CategoriesResponseDTO> getCategories()
  +Future<ProductsResponseDTO> getAllNewAddedProducts()
  +Future<ProductsResponseDTO> getProductsByCategory()
  +Future<ProductDetailsResponseDTO> getProductDetails()
  +Future<ProductsResponseDTO> getSearchedProducts()
  +Future<CartItemsResponseDTO> getCartItems()
  +Future<CartUpdateResponseDTO> addProductToCart()
  +Future<CartUpdateResponseDTO> deleteProductFromCart()
  +Future<OrderResponseDTO?> placeOrder()
}

"ecommerce::Data::Api::ApiManager.dart::ApiManager" o-- "ecommerce::Data::Api::ApiManager.dart::ApiManager"

class "ecommerce::Data::Data%20Source::AuthRemoteDataSourceImpl.dart::AuthRemoteDataSourceImpl" {
  +ApiManager apiManager
  +Future<CreateUserResponse?> addNewUser()
  +Future<String> uploadUserImage()
  +Future<LoginResponse> login()
}

"ecommerce::Data::Data%20Source::AuthRemoteDataSourceImpl.dart::AuthRemoteDataSourceImpl" o-- "ecommerce::Data::Api::ApiManager.dart::ApiManager"
"ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRemoteDataSource" <|-- "ecommerce::Data::Data%20Source::AuthRemoteDataSourceImpl.dart::AuthRemoteDataSourceImpl"

class "ecommerce::Data::Data%20Source::CategoriesRemoteDataSource.dart::CategoriesRemoteDataSourceImpl" {
  +ApiManager apiManager
  +Future<CategoriesResponse> getCategories()
}

"ecommerce::Data::Data%20Source::CategoriesRemoteDataSource.dart::CategoriesRemoteDataSourceImpl" o-- "ecommerce::Data::Api::ApiManager.dart::ApiManager"
"ecommerce::Domain::Repository::Categories_Repository_Contract.dart::CategoriesRemoteDataSource" <|-- "ecommerce::Data::Data%20Source::CategoriesRemoteDataSource.dart::CategoriesRemoteDataSourceImpl"

class "ecommerce::Data::Data%20Source::OrdersRemoteDataSourceImpl.dart::OrdersRemoteDataSourceImpl" {
  +ApiManager apiManager
  +Future<OrderResponse> placeOrder()
}

"ecommerce::Data::Data%20Source::OrdersRemoteDataSourceImpl.dart::OrdersRemoteDataSourceImpl" o-- "ecommerce::Data::Api::ApiManager.dart::ApiManager"
"ecommerce::Domain::Repository::Orders_Repository_Contract.dart::OrdersRemoteDataSource" <|-- "ecommerce::Data::Data%20Source::OrdersRemoteDataSourceImpl.dart::OrdersRemoteDataSourceImpl"

class "ecommerce::Data::Data%20Source::ProductLocalDataSourceImpl.dart::ProductLocalDataSourceImpl" {
  +SQLdb sqLdb
  +Future<String> insertData()
  +Future<String> deleteData()
  +Future<List<Product>?> readData()
}

"ecommerce::Data::Data%20Source::ProductLocalDataSourceImpl.dart::ProductLocalDataSourceImpl" o-- "ecommerce::Data::SQL::SQLDB.dart::SQLdb"
"ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductLocalDataSource" <|-- "ecommerce::Data::Data%20Source::ProductLocalDataSourceImpl.dart::ProductLocalDataSourceImpl"

class "ecommerce::Data::Data%20Source::ProductRemoteDataSourceImpl.dart::ProductRemoteDataSourceImpl" {
  +ApiManager apiManager
  +Future<ProductsResponse> getNewAddedProduct()
  +Future<ProductsResponse> getProductsByCategory()
  +Future<ProductDetailsResponse> getProductDetails()
  +Future<ProductsResponse> search()
  +Future<CartItemsResponse> getCartData()
  +Future<CartUpdateResponse> addToCart()
  +Future<CartUpdateResponse> deleteFromCart()
}

"ecommerce::Data::Data%20Source::ProductRemoteDataSourceImpl.dart::ProductRemoteDataSourceImpl" o-- "ecommerce::Data::Api::ApiManager.dart::ApiManager"
"ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRemoteDataSource" <|-- "ecommerce::Data::Data%20Source::ProductRemoteDataSourceImpl.dart::ProductRemoteDataSourceImpl"

class "ecommerce::Data::Models::Cart::CartItemDTO.dart::CartItemDTO" {
  +int? userId
  +String? productId
  +int? id
  +Map<String, dynamic> toJson()
  +CartItem toDomain()
}

class "ecommerce::Data::Models::Cart::CartItemsResponseDTO.dart::CartItemsResponseDTO" {
  +String? status
  +String? message
  +List<CartProductsDTO>? cartProducts
  +Map<String, dynamic> toJson()
  +CartItemsResponse toDomain()
}

class "ecommerce::Data::Models::Cart::CartProductDTO.dart::CartProductDTO" {
  +num? id
  +String? name
  +num? category
  +num? price
  +String? mainImage
  +num? brand
  +num? quantity
  +num? rating
  +Map<String, dynamic> toJson()
  +CartProduct toDomain()
}

class "ecommerce::Data::Models::Cart::CartProductsDTO.dart::CartProductsDTO" {
  +num? id
  +num? productId
  +num? userId
  +CartProductDTO? cartProduct
  +Map<String, dynamic> toJson()
  +CartProducts toDomain()
}

"ecommerce::Data::Models::Cart::CartProductsDTO.dart::CartProductsDTO" o-- "ecommerce::Data::Models::Cart::CartProductDTO.dart::CartProductDTO"

class "ecommerce::Data::Models::Cart::CartUpdateResponseDTO.dart::CartUpdateResponseDTO" {
  +int? code
  +String? message
  +CartItemDTO? cartItem
  +Map<String, dynamic> toJson()
  +CartUpdateResponse toDomain()
}

"ecommerce::Data::Models::Cart::CartUpdateResponseDTO.dart::CartUpdateResponseDTO" o-- "ecommerce::Data::Models::Cart::CartItemDTO.dart::CartItemDTO"

class "ecommerce::Data::Models::Categories::CategoriesDTO.dart::CategoriesDTO" {
  +num? id
  +String? name
  +String? image
  +Map<String, dynamic> toJson()
  +Categories toDomain()
}

class "ecommerce::Data::Models::Categories::CategoriesResponseDTO.dart::CategoriesResponseDTO" {
  +String? statusCode
  +String? message
  +List<CategoriesDTO>? categories
  +Map<String, dynamic> toJson()
  +CategoriesResponse toDomain()
}

class "ecommerce::Data::Models::Order::OrderDTO.dart::OrderDTO" {
  +String? token
  +String? name
  +String? phoneNumber
  +String? address
  +String? cardNumber
  +String? shippingState
  +double? shippingPrice
  +String? postalCode
  +double? total
  +List<OrderProductsDTO>? products
  +Map<String, dynamic> toJson()
}

class "ecommerce::Data::Models::Order::OrderProductsDTO.dart::OrderProductsDTO" {
  +int? id
  +int? quantity
  +double? orderTotal
  +Map<String, dynamic> toJson()
}

class "ecommerce::Data::Models::Order::OrderResponseDTO.dart::OrderResponseDTO" {
  +int? statusCode
  +String? message
  +int? orderNumber
  +String? userName
  +int? total
  +int? shippingCharge
  +Map<String, dynamic> toJson()
  +OrderResponse toDomain()
}

class "ecommerce::Data::Models::Products::FeedBackDTO.dart::FeedBackDTO" {
  +String? user
  +num? rate
  +String? comment
  +String? userImage
  +Map<String, dynamic> toJson()
  +FeedBack toDomain()
}

class "ecommerce::Data::Models::Products::ProductDetailsDTO.dart::ProductDetailsDTO" {
  +num? id
  +String? name
  +String? category
  +num? price
  +String? mainImage
  +String? description
  +String? descriptionImage
  +String? brand
  +num? quantity
  +num? rating
  +num? userRating
  +String? userComment
  +List<FeedBackDTO>? feedBack
  +List<String>? images
  +Map<String, dynamic> toJson()
  +ProductDetails toDomain()
}

class "ecommerce::Data::Models::Products::ProductDetailsResponseDTO.dart::ProductDetailsResponseDTO" {
  +String? status
  +String? message
  +ProductDetailsDTO? product
  +Map<String, dynamic> toJson()
  +ProductDetailsResponse toDomain()
}

"ecommerce::Data::Models::Products::ProductDetailsResponseDTO.dart::ProductDetailsResponseDTO" o-- "ecommerce::Data::Models::Products::ProductDetailsDTO.dart::ProductDetailsDTO"

class "ecommerce::Data::Models::Products::ProductsDTO.dart::ProductsDTO" {
  +num? id
  +String? name
  +String? category
  +num? price
  +String? mainImage
  +String? brand
  +num? rating
  +Map<String, dynamic> toJson()
  +Product toDomain()
}

class "ecommerce::Data::Models::Products::ProductsResponseDTO.dart::ProductsResponseDTO" {
  +String? status
  +String? message
  +num? page
  +List<ProductsDTO>? products
  +Map<String, dynamic> toJson()
  +ProductsResponse toDomain()
}

class "ecommerce::Data::Models::User::CreateUserResponseDTO.dart::CreateUserResponseDTO" {
  +String? statusCode
  +String? message
  +UserDTO? user
  +Map<String, dynamic> toJson()
  +CreateUserResponse toDomain()
}

"ecommerce::Data::Models::User::CreateUserResponseDTO.dart::CreateUserResponseDTO" o-- "ecommerce::Data::Models::User::UserDTO.dart::UserDTO"

class "ecommerce::Data::Models::User::LoginResponseDTO.dart::LoginResponseDTO" {
  +String? statusCode
  +String? message
  +String? token
  +Map<String, dynamic> toJson()
  +LoginResponse toDomain()
}

class "ecommerce::Data::Models::User::UserDTO.dart::UserDTO" {
  +String? name
  +String? email
  +String? password
  +String? phone
  +String? birthDate
  +String? token
  +Map<String, dynamic> toJson()
}

class "ecommerce::Data::Repository::AuthRepositoryImpl.dart::AuthRepositoryImpl" {
  +AuthRemoteDataSource remoteDataSource
  +Future<CreateUserResponse> addNewUser()
  +Future<String> uploadUserImage()
  +Future<LoginResponse> login()
}

"ecommerce::Data::Repository::AuthRepositoryImpl.dart::AuthRepositoryImpl" o-- "ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRemoteDataSource"
"ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRepository" <|-- "ecommerce::Data::Repository::AuthRepositoryImpl.dart::AuthRepositoryImpl"

class "ecommerce::Data::Repository::CategoriesRepository.dart::CategoriesRepositoryImpl" {
  +CategoriesRemoteDataSource remoteDataSource
  +Future<CategoriesResponse> getCategories()
}

"ecommerce::Data::Repository::CategoriesRepository.dart::CategoriesRepositoryImpl" o-- "ecommerce::Domain::Repository::Categories_Repository_Contract.dart::CategoriesRemoteDataSource"
"ecommerce::Domain::Repository::Categories_Repository_Contract.dart::CategoriesRepository" <|-- "ecommerce::Data::Repository::CategoriesRepository.dart::CategoriesRepositoryImpl"

class "ecommerce::Data::Repository::OrdersRepositoryImpl.dart::OrdersRepositoryImpl" {
  +OrdersRemoteDataSource remoteDataSource
  +Future<OrderResponse> placeOrder()
}

"ecommerce::Data::Repository::OrdersRepositoryImpl.dart::OrdersRepositoryImpl" o-- "ecommerce::Domain::Repository::Orders_Repository_Contract.dart::OrdersRemoteDataSource"
"ecommerce::Domain::Repository::Orders_Repository_Contract.dart::OrdersRepository" <|-- "ecommerce::Data::Repository::OrdersRepositoryImpl.dart::OrdersRepositoryImpl"

class "ecommerce::Data::Repository::ProductRepositoryImpl.dart::ProductRepositoryImpl" {
  +ProductRemoteDataSource remoteDataSource
  +ProductLocalDataSource localDataSource
  +Future<List<Product>?> getNewAddedProduct()
  +Future<List<Product>?> getProductsByCategory()
  +Future<ProductDetails?> getProductDetails()
  +Future<String> insertData()
  +Future<String> deleteData()
  +Future<List<Product>?> readData()
  +Future<List<Product>?> search()
  +Future<List<CartProducts>?> getCartData()
  +Future<String?> addToCart()
  +Future<String?> deleteFromCart()
}

"ecommerce::Data::Repository::ProductRepositoryImpl.dart::ProductRepositoryImpl" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRemoteDataSource"
"ecommerce::Data::Repository::ProductRepositoryImpl.dart::ProductRepositoryImpl" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductLocalDataSource"
"ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository" <|-- "ecommerce::Data::Repository::ProductRepositoryImpl.dart::ProductRepositoryImpl"

class "ecommerce::Data::SQL::SQLDB.dart::SQLdb" {
  {static} -Database? _db
  +Future<Database?> getDB()
  +dynamic initiateDB()
  -void _onCreate()
  +Future<String> insertData()
  +Future<String> deleteData()
  +dynamic readData()
}

"ecommerce::Data::SQL::SQLDB.dart::SQLdb" o-- "sqflite_common::sqlite_api.dart::Database"

class "ecommerce::Domain::Models::Cart::CartItem.dart::CartItem" {
  +int? userId
  +String? productId
  +int? id
}

class "ecommerce::Domain::Models::Cart::CartItemsResponse.dart::CartItemsResponse" {
  +String? status
  +String? message
  +List<CartProducts>? cartProducts
}

class "ecommerce::Domain::Models::Cart::CartProduct.dart::CartProduct" {
  +num? id
  +String? name
  +num? category
  +num? price
  +String? mainImage
  +num? brand
  +num? quantity
  +num? rating
  +int? orderedQuantity
}

class "ecommerce::Domain::Models::Cart::CartProducts.dart::CartProducts" {
  +num? id
  +num? productId
  +num? userId
  +CartProduct? cartProduct
}

"ecommerce::Domain::Models::Cart::CartProducts.dart::CartProducts" o-- "ecommerce::Domain::Models::Cart::CartProduct.dart::CartProduct"

class "ecommerce::Domain::Models::Cart::CartUpdateResponse.dart::CartUpdateResponse" {
  +int? code
  +String? message
  +CartItem? cartItem
}

"ecommerce::Domain::Models::Cart::CartUpdateResponse.dart::CartUpdateResponse" o-- "ecommerce::Domain::Models::Cart::CartItem.dart::CartItem"

class "ecommerce::Domain::Models::Categories::Categories.dart::Categories" {
  +num? id
  +String? name
  +String? image
}

class "ecommerce::Domain::Models::Categories::CategoriesResponse.dart::CategoriesResponse" {
  +String? statusCode
  +String? message
  +List<Categories>? categories
}

class "ecommerce::Domain::Models::Order::Order.dart::Order" {
  +String? token
  +String? name
  +String? phoneNumber
  +String? address
  +String? cardNumber
  +String? shippingState
  +double? shippingPrice
  +String? postalCode
  +double? total
  +List<OrderProducts>? products
  +OrderDTO toData()
}

class "ecommerce::Domain::Models::Order::OrderProducts.dart::OrderProducts" {
  +int? id
  +int? quantity
  +double? orderTotal
  +OrderProductsDTO toData()
}

class "ecommerce::Domain::Models::Order::OrderResponse.dart::OrderResponse" {
  +int? statusCode
  +String? message
  +int? orderNumber
  +String? userName
  +int? total
  +int? shippingCharge
}

class "ecommerce::Domain::Models::Products::FeedBack.dart::FeedBack" {
  +String? user
  +num? rate
  +String? comment
  +String? userImage
}

class "ecommerce::Domain::Models::Products::Prdouct.dart::Product" {
  +num? id
  +String? name
  +String? category
  +num? price
  +String? mainImage
  +String? brand
  +num? rating
  +bool? isInWishList
}

class "ecommerce::Domain::Models::Products::ProductDetails.dart::ProductDetails" {
  +num? id
  +String? name
  +String? category
  +num? price
  +String? mainImage
  +String? description
  +String? descriptionImage
  +String? brand
  +num? quantity
  +num? rating
  +num? userRating
  +String? userComment
  +List<FeedBack>? feedBack
  +List<String>? images
}

class "ecommerce::Domain::Models::Products::ProductDetailsResponse.dart::ProductDetailsResponse" {
  +String? status
  +String? message
  +ProductDetails? product
}

"ecommerce::Domain::Models::Products::ProductDetailsResponse.dart::ProductDetailsResponse" o-- "ecommerce::Domain::Models::Products::ProductDetails.dart::ProductDetails"

class "ecommerce::Domain::Models::Products::ProductsResponse.dart::ProductsResponse" {
  +String? status
  +String? message
  +List<Product>? products
}

class "ecommerce::Domain::Models::User::CreateUserResponse.dart::CreateUserResponse" {
  +String? statusCode
  +String? message
  +String? token
}

class "ecommerce::Domain::Models::User::LoginResponse.dart::LoginResponse" {
  +String? statusCode
  +String? message
  +String? token
}

abstract class "ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRemoteDataSource" {
  +Future<CreateUserResponse?> addNewUser()
  +Future<String> uploadUserImage()
  +Future<LoginResponse> login()
}

abstract class "ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRepository" {
  +Future<CreateUserResponse?> addNewUser()
  +Future<String> uploadUserImage()
  +Future<LoginResponse> login()
}

abstract class "ecommerce::Domain::Repository::Categories_Repository_Contract.dart::CategoriesRemoteDataSource" {
  +Future<CategoriesResponse> getCategories()
}

abstract class "ecommerce::Domain::Repository::Categories_Repository_Contract.dart::CategoriesRepository" {
  +Future<CategoriesResponse> getCategories()
}

abstract class "ecommerce::Domain::Repository::Orders_Repository_Contract.dart::OrdersRemoteDataSource" {
  +Future<OrderResponse> placeOrder()
}

abstract class "ecommerce::Domain::Repository::Orders_Repository_Contract.dart::OrdersRepository" {
  +Future<OrderResponse> placeOrder()
}

abstract class "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRemoteDataSource" {
  +Future<ProductsResponse> getNewAddedProduct()
  +Future<ProductsResponse> getProductsByCategory()
  +Future<ProductDetailsResponse> getProductDetails()
  +Future<ProductsResponse> search()
  +Future<CartItemsResponse> getCartData()
  +Future<CartUpdateResponse> addToCart()
  +Future<CartUpdateResponse> deleteFromCart()
}

abstract class "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository" {
  +Future<List<Product>?> getNewAddedProduct()
  +Future<List<Product>?> getProductsByCategory()
  +Future<ProductDetails?> getProductDetails()
  +Future<String> insertData()
  +Future<String> deleteData()
  +Future<List<Product>?> readData()
  +Future<List<Product>?> search()
  +Future<List<CartProducts>?> getCartData()
  +Future<String?> addToCart()
  +Future<String?> deleteFromCart()
}

abstract class "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductLocalDataSource" {
  +Future<String> insertData()
  +Future<String> deleteData()
  +Future<List<Product>?> readData()
}

class "ecommerce::Domain::UseCase::AddProductToCartUseCase.dart::AddProductToCartUseCase" {
  +ProductRepository repository
  +Future<String?> invoke()
}

"ecommerce::Domain::UseCase::AddProductToCartUseCase.dart::AddProductToCartUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::AddToWishListUseCase.dart::AddToWishListUseCase" {
  +ProductRepository repository
  +Future<String> invoke()
}

"ecommerce::Domain::UseCase::AddToWishListUseCase.dart::AddToWishListUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::AuthLoginUserCase.dart::AuthLoginUserCase" {
  +AuthRepository repository
  +Future<LoginResponse> login()
}

"ecommerce::Domain::UseCase::AuthLoginUserCase.dart::AuthLoginUserCase" o-- "ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRepository"

class "ecommerce::Domain::UseCase::AuthRegistrationUseCase.dart::AuthRegistrationUseCase" {
  +AuthRepository repository
  +Future<CreateUserResponse> invoke()
}

"ecommerce::Domain::UseCase::AuthRegistrationUseCase.dart::AuthRegistrationUseCase" o-- "ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRepository"

class "ecommerce::Domain::UseCase::AuthUploadUserImageUseCase.dart::AuthUploadUserImageUseCase" {
  +AuthRepository repository
  +Future<String> uploadUserImage()
}

"ecommerce::Domain::UseCase::AuthUploadUserImageUseCase.dart::AuthUploadUserImageUseCase" o-- "ecommerce::Domain::Repository::Auth_Ropository_Contract.dart::AuthRepository"

class "ecommerce::Domain::UseCase::DeleteFromWishListUseCase.dart::DeleteFromWishListUseCase" {
  +ProductRepository repository
  +Future<String> invoke()
}

"ecommerce::Domain::UseCase::DeleteFromWishListUseCase.dart::DeleteFromWishListUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::DeleteProductFromCartUseCase.dart::DeleteProductFromCartUseCase" {
  +ProductRepository repository
  +Future<String?> invoke()
}

"ecommerce::Domain::UseCase::DeleteProductFromCartUseCase.dart::DeleteProductFromCartUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::GetCartItemsUseCase.dart::GetCartItemsUseCase" {
  +ProductRepository repository
  +Future<List<CartProducts>?> invoke()
}

"ecommerce::Domain::UseCase::GetCartItemsUseCase.dart::GetCartItemsUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::GetCategoriesUseCase.dart::GetCategoriesUseCase" {
  +CategoriesRepository categoriesRepository
  +Future<CategoriesResponse> invoke()
}

"ecommerce::Domain::UseCase::GetCategoriesUseCase.dart::GetCategoriesUseCase" o-- "ecommerce::Domain::Repository::Categories_Repository_Contract.dart::CategoriesRepository"

class "ecommerce::Domain::UseCase::GetNewAddedProductUseCase.dart::GetNewAddedProductsUseCase" {
  +ProductRepository repository
  +Future<List<Product>?> invoke()
}

"ecommerce::Domain::UseCase::GetNewAddedProductUseCase.dart::GetNewAddedProductsUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::GetProductDetailsUseCase.dart::GetProductDetailsUseCase" {
  +ProductRepository repository
  +Future<ProductDetails?> invoke()
}

"ecommerce::Domain::UseCase::GetProductDetailsUseCase.dart::GetProductDetailsUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::GetProductsByCategoryIdUseCase.dart::GetProductsByCategoryIdUseCase" {
  +ProductRepository repository
  +Future<List<Product>?> invoke()
}

"ecommerce::Domain::UseCase::GetProductsByCategoryIdUseCase.dart::GetProductsByCategoryIdUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::GetWishListProductsUseCase.dart::GetWishListProductsUseCase" {
  +ProductRepository repository
  +Future<List<Product>?> invoke()
}

"ecommerce::Domain::UseCase::GetWishListProductsUseCase.dart::GetWishListProductsUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::Domain::UseCase::PlaceOrderUseCase.dart::PlaceOrderUseCase" {
  +OrdersRepository repository
  +Future<OrderResponse> invoke()
}

"ecommerce::Domain::UseCase::PlaceOrderUseCase.dart::PlaceOrderUseCase" o-- "ecommerce::Domain::Repository::Orders_Repository_Contract.dart::OrdersRepository"

class "ecommerce::Domain::UseCase::SearchForProductUseCase.dart::SearchForProductUseCase" {
  +ProductRepository repository
  +Future<List<Product>?> invoke()
}

"ecommerce::Domain::UseCase::SearchForProductUseCase.dart::SearchForProductUseCase" o-- "ecommerce::Domain::Repository::Products_Prepository_Contract.dart::ProductRepository"

class "ecommerce::main.dart::MyApp" {
  +String token
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::main.dart::MyApp"

class "ecommerce::Presentation::UI::Global%20Widgets::errorWidget.dart::errorWidget" {
  +String errorMessage
  +Function onTryAgainPress
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Global%20Widgets::errorWidget.dart::errorWidget"

class "ecommerce::Presentation::UI::Global%20Widgets::PoductShowWidget.dart::ProductShowWidget" {
  +Product product
  +Function onViewNowPress
  +Function onSlidablePress
  +Widget build()
}

"ecommerce::Presentation::UI::Global%20Widgets::PoductShowWidget.dart::ProductShowWidget" o-- "ecommerce::Domain::Models::Products::Prdouct.dart::Product"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Global%20Widgets::PoductShowWidget.dart::ProductShowWidget"

class "ecommerce::Presentation::UI::Global%20Widgets::ProductWidget.dart::ProductWidget" {
  +Product product
  +Function onWidgetPress
  +Function onFavoritePress
  +State<ProductWidget> createState()
}

"ecommerce::Presentation::UI::Global%20Widgets::ProductWidget.dart::ProductWidget" o-- "ecommerce::Domain::Models::Products::Prdouct.dart::Product"
"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Global%20Widgets::ProductWidget.dart::ProductWidget"

class "ecommerce::Presentation::UI::Global%20Widgets::ProductWidget.dart::_ProductWidgetState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Global%20Widgets::ProductWidget.dart::_ProductWidgetState"

class "ecommerce::Presentation::UI::Home::HomeScreenView.dart::HomeScreen" {
  {static} +String routeName
  +State<HomeScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Home::HomeScreenView.dart::HomeScreen"

class "ecommerce::Presentation::UI::Home::HomeScreenView.dart::_HomeScreenState" {
  +List<Widget> tabs
  +int selectedIndex
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Home::HomeScreenView.dart::_HomeScreenState"

abstract class "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabNavigator.dart::CartTabNavigator" {
  +void showLoading()
  +void hideDialog()
  +void showSuccessMessage()
  +void goToPaymentScreen()
}

class "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabVIew.dart::CartTabView" {
  +State<CartTabView> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabVIew.dart::CartTabView"

class "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabVIew.dart::_CartTabViewState" {
  +CartTabViewModel viewModel
  +void initState()
  +void dispose()
  +Widget build()
  +void hideDialog()
  +void showLoading()
  +void showSuccessMessage()
  +void goToPaymentScreen()
}

"ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabVIew.dart::_CartTabViewState" o-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabViewModel.dart::CartTabViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabVIew.dart::_CartTabViewState"
"ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabNavigator.dart::CartTabNavigator" <|-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabVIew.dart::_CartTabViewState"

class "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabViewModel.dart::CartTabViewModel" {
  +GetCartItemsUseCase getCartItemsUseCase
  +DeleteProductFromCartUseCase deleteProductFormCartUseCase
  +CartTabNavigator? navigator
  +String? errorMessage
  +List<CartProducts>? products
  +AppConfigProvider? provider
  +void getCartItems()
  +void onTryAgainPress()
  +int onPlusButtonPress()
  +int onMinusButtonPress()
  +double calcTotal()
  +void onSlidablePress()
  +void onGoToPaymentPress()
}

"ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabViewModel.dart::CartTabViewModel" o-- "ecommerce::Domain::UseCase::GetCartItemsUseCase.dart::GetCartItemsUseCase"
"ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabViewModel.dart::CartTabViewModel" o-- "ecommerce::Domain::UseCase::DeleteProductFromCartUseCase.dart::DeleteProductFromCartUseCase"
"ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabViewModel.dart::CartTabViewModel" o-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabNavigator.dart::CartTabNavigator"
"ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabViewModel.dart::CartTabViewModel" o-- "ecommerce::Core::Provider::AppConfigProvider.dart::AppConfigProvider"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::CartTabViewModel.dart::CartTabViewModel"

class "ecommerce::Presentation::UI::Home::Tabs::CartTab::Widgets::CartItemWidget.dart::CartItemWidget" {
  +int productIndex
  +Function onSlibablePress
  +Function onPlusButtonPress
  +Function onMinusButtonPress
  +State<CartItemWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::Widgets::CartItemWidget.dart::CartItemWidget"

class "ecommerce::Presentation::UI::Home::Tabs::CartTab::Widgets::CartItemWidget.dart::_CartItemWidgetState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Home::Tabs::CartTab::Widgets::CartItemWidget.dart::_CartItemWidgetState"

abstract class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabNavigator.dart::HomeTabNavigator" {
  +void goToProductListScreen()
  +void goToProductDetailsScreen()
  +void showLoading()
  +void hideDialog()
  +void showSuccessMessage()
}

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabView.dart::HomeTabView" {
  +State<HomeTabView> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabView.dart::HomeTabView"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabView.dart::_HomeTabViewState" {
  +HomeTabViewModel viewModel
  +void initState()
  +void dispose()
  +Widget build()
  +void goToProductListScreen()
  +void goToProductDetailsScreen()
  +void hideDialog()
  +void showLoading()
  +void showSuccessMessage()
}

"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabView.dart::_HomeTabViewState" o-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabView.dart::_HomeTabViewState"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabNavigator.dart::HomeTabNavigator" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabView.dart::_HomeTabViewState"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel" {
  +GetCategoriesUseCase categoriesUseCase
  +GetNewAddedProductsUseCase newAddedProductsUseCase
  +AddToWishListUseCase addToWishListUseCase
  +DeleteFromWishListUseCase deleteFromWishListUseCase
  +HomeTabNavigator? navigator
  +String? errorMessage
  +List<Categories>? categories
  +List<Product>? products
  +SQLdb sqLdb
  +void getCategories()
  +void getNewAddedProducts()
  +void onTryAgainButtonPress()
  +void goToProductsListScreen()
  +void onWidgetPress()
  +void onFavoritePress()
}

"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel" o-- "ecommerce::Domain::UseCase::GetCategoriesUseCase.dart::GetCategoriesUseCase"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel" o-- "ecommerce::Domain::UseCase::GetNewAddedProductUseCase.dart::GetNewAddedProductsUseCase"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel" o-- "ecommerce::Domain::UseCase::AddToWishListUseCase.dart::AddToWishListUseCase"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel" o-- "ecommerce::Domain::UseCase::DeleteFromWishListUseCase.dart::DeleteFromWishListUseCase"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel" o-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabNavigator.dart::HomeTabNavigator"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel" o-- "ecommerce::Data::SQL::SQLDB.dart::SQLdb"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::HomeTabViewModel.dart::HomeTabViewModel"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerSlideShow.dart::BannerSlideShow" {
  +List<BannerData> bannersData
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerSlideShow.dart::BannerSlideShow"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerSlideShow.dart::BannerData" {
  +int id
  +AlignmentGeometry alignmentGeometry
  +String title
  +String titleOnButton
  +String image
  +Color textColor
  +Categories categories
}

"ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerSlideShow.dart::BannerData" o-- "flutter::src::painting::alignment.dart::AlignmentGeometry"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerSlideShow.dart::BannerData" o-- "dart::ui::Color"
"ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerSlideShow.dart::BannerData" o-- "ecommerce::Domain::Models::Categories::Categories.dart::Categories"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerWiget.dart::BannerWidget" {
  +BannerData bannerData
  +Widget build()
}

"ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerWiget.dart::BannerWidget" o-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerSlideShow.dart::BannerData"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::BannerWiget.dart::BannerWidget"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::Categories.dart::CategoriesList" {
  +List<Categories> categories
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::Categories.dart::CategoriesList"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::CategoryShowWidget.dart::CategoryShowWidget" {
  +Categories categories
  +Widget build()
}

"ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::CategoryShowWidget.dart::CategoryShowWidget" o-- "ecommerce::Domain::Models::Categories::Categories.dart::Categories"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::CategoryShowWidget.dart::CategoryShowWidget"

class "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::ProductList.dart::HomeProductList" {
  +List<Product> products
  +Function onProductPress
  +Function onFavoritePress
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::HomeTab::Widgets::ProductList.dart::HomeProductList"

class "ecommerce::Presentation::UI::Home::Tabs::ProfileTab::ProfileTabView.dart::ProfileTabView" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::ProfileTab::ProfileTabView.dart::ProfileTabView"

abstract class "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabNavigator.dart::SearchTabNavigator" {
  +void goToDetailsScreen()
  +void showLoading()
  +void hideDialog()
  +void showSuccessMessage()
}

class "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabView.dart::SearchTabView" {
  +State<SearchTabView> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabView.dart::SearchTabView"

class "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabView.dart::_SearchTabViewState" {
  +SearchTabViewModel viewModel
  +ScrollController controller
  +void initState()
  +void dispose()
  +Widget build()
  +void goToDetailsScreen()
  +void hideDialog()
  +void showLoading()
  +void showSuccessMessage()
}

"ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabView.dart::_SearchTabViewState" o-- "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabViewModel.dart::SearchTabViewModel"
"ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabView.dart::_SearchTabViewState" o-- "flutter::src::widgets::scroll_controller.dart::ScrollController"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabView.dart::_SearchTabViewState"
"ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabNavigator.dart::SearchTabNavigator" <|-- "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabView.dart::_SearchTabViewState"

class "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabViewModel.dart::SearchTabViewModel" {
  +SearchForProductUseCase searchForProductUseCase
  +AddToWishListUseCase addToWishListUseCase
  +DeleteFromWishListUseCase deleteFromWishListUseCase
  +String? errorMessage
  +List<Product>? products
  +SearchTabNavigator? navigator
  +void getProducts()
  +void onViewNowPress()
  +void onSlidablePress()
}

"ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabViewModel.dart::SearchTabViewModel" o-- "ecommerce::Domain::UseCase::SearchForProductUseCase.dart::SearchForProductUseCase"
"ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabViewModel.dart::SearchTabViewModel" o-- "ecommerce::Domain::UseCase::AddToWishListUseCase.dart::AddToWishListUseCase"
"ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabViewModel.dart::SearchTabViewModel" o-- "ecommerce::Domain::UseCase::DeleteFromWishListUseCase.dart::DeleteFromWishListUseCase"
"ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabViewModel.dart::SearchTabViewModel" o-- "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabNavigator.dart::SearchTabNavigator"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::Home::Tabs::SearchTab::SearchTabViewModel.dart::SearchTabViewModel"

abstract class "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabNavigator.dart::WishListTabNavigator" {
  +void goToProductDetailsScreen()
  +void showLoading()
  +void hideDialog()
  +void showSuccessMessage()
}

class "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabView.dart::WishListTabView" {
  +State<WishListTabView> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabView.dart::WishListTabView"

class "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabView.dart::_WishListTabViewState" {
  +WishListTabViewModel viewModel
  +void initState()
  +void dispose()
  +Widget build()
  +void goToProductDetailsScreen()
  +void hideDialog()
  +void showLoading()
  +void showSuccessMessage()
}

"ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabView.dart::_WishListTabViewState" o-- "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabViewModel.dart::WishListTabViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabView.dart::_WishListTabViewState"
"ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabNavigator.dart::WishListTabNavigator" <|-- "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabView.dart::_WishListTabViewState"

class "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabViewModel.dart::WishListTabViewModel" {
  +GetWishListProductsUseCase getWishListProductsUseCase
  +DeleteFromWishListUseCase deleteFromWishListUseCase
  +AddToWishListUseCase addToWishListUseCase
  +WishListTabNavigator? navigator
  +List<Product>? products
  +String? errorMessage
  +void getProducts()
  +void onTryAgainPress()
  +void onViewNowPress()
  +void onSlidablePress()
}

"ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabViewModel.dart::WishListTabViewModel" o-- "ecommerce::Domain::UseCase::GetWishListProductsUseCase.dart::GetWishListProductsUseCase"
"ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabViewModel.dart::WishListTabViewModel" o-- "ecommerce::Domain::UseCase::DeleteFromWishListUseCase.dart::DeleteFromWishListUseCase"
"ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabViewModel.dart::WishListTabViewModel" o-- "ecommerce::Domain::UseCase::AddToWishListUseCase.dart::AddToWishListUseCase"
"ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabViewModel.dart::WishListTabViewModel" o-- "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabNavigator.dart::WishListTabNavigator"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::Home::Tabs::WithLIstTab::WishListTabViewModel.dart::WishListTabViewModel"

abstract class "ecommerce::Presentation::UI::Login::LoginScreenNavigator.dart::LoginScreenNavigator" {
  +dynamic goToCreateAccountScreen()
  +dynamic goToHomeScreen()
  +dynamic showErrorMessage()
  +dynamic showSuccessMessage()
  +dynamic showLoading()
  +dynamic updateToken()
  +dynamic hideDialog()
}

class "ecommerce::Presentation::UI::Login::LoginScreenView.dart::LoginScreen" {
  {static} +String routeName
  +State<LoginScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Login::LoginScreenView.dart::LoginScreen"

class "ecommerce::Presentation::UI::Login::LoginScreenView.dart::_LoginScreenState" {
  +LoginScreenViweModel viewModel
  +GlobalKey<FormState> formKey
  +TextEditingController emailController
  +TextEditingController passwordController
  +bool isVisible
  +void initState()
  +void dispose()
  +Widget build()
  +dynamic goToCreateAccountScreen()
  +dynamic goToHomeScreen()
  +dynamic showErrorMessage()
  +dynamic hideDialog()
  +dynamic showLoading()
  +dynamic showSuccessMessage()
  +dynamic updateToken()
}

"ecommerce::Presentation::UI::Login::LoginScreenView.dart::_LoginScreenState" o-- "ecommerce::Presentation::UI::Login::LoginScreenViewModel.dart::LoginScreenViweModel"
"ecommerce::Presentation::UI::Login::LoginScreenView.dart::_LoginScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"ecommerce::Presentation::UI::Login::LoginScreenView.dart::_LoginScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Login::LoginScreenView.dart::_LoginScreenState"
"ecommerce::Presentation::UI::Login::LoginScreenNavigator.dart::LoginScreenNavigator" <|-- "ecommerce::Presentation::UI::Login::LoginScreenView.dart::_LoginScreenState"

class "ecommerce::Presentation::UI::Login::LoginScreenViewModel.dart::LoginScreenViweModel" {
  +AuthLoginUserCase useCase
  +LoginScreenNavigator? navigator
  +String? emailValidation()
  +String? passwordValidation()
  +void onLoginButtonPress()
  +void onCreateAccountButtonPress()
  +void goToHome()
}

"ecommerce::Presentation::UI::Login::LoginScreenViewModel.dart::LoginScreenViweModel" o-- "ecommerce::Domain::UseCase::AuthLoginUserCase.dart::AuthLoginUserCase"
"ecommerce::Presentation::UI::Login::LoginScreenViewModel.dart::LoginScreenViweModel" o-- "ecommerce::Presentation::UI::Login::LoginScreenNavigator.dart::LoginScreenNavigator"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::Login::LoginScreenViewModel.dart::LoginScreenViweModel"

abstract class "ecommerce::Presentation::UI::Payment::PaymentNavigator.dart::PaymentNavigator" {
  +void goToHomeScreen()
  +void showErrorMessage()
  +void showSuccessMessage()
  +void showLoading()
  +void hideDialog()
}

class "ecommerce::Presentation::UI::Payment::PaymentView.dart::PaymentScreen" {
  {static} +String routeName
  +State<PaymentScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Payment::PaymentView.dart::PaymentScreen"

class "ecommerce::Presentation::UI::Payment::PaymentView.dart::_PaymentScreenState" {
  +List<Widget> tabs
  +List<String> titles
  +PaymentViewModel viewModel
  +void initState()
  +void dispose()
  +Widget build()
  +void goToHomeScreen()
  +void hideDialog()
  +void showErrorMessage()
  +void showLoading()
  +void showSuccessMessage()
}

"ecommerce::Presentation::UI::Payment::PaymentView.dart::_PaymentScreenState" o-- "ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Payment::PaymentView.dart::_PaymentScreenState"
"ecommerce::Presentation::UI::Payment::PaymentNavigator.dart::PaymentNavigator" <|-- "ecommerce::Presentation::UI::Payment::PaymentView.dart::_PaymentScreenState"

class "ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel" {
  +PlaceOrderUseCase useCase
  +int selectedIndex
  +PaymentNavigator? navigator
  +List<OrderProducts>? products
  +GlobalKey<FormState> formKey
  +GlobalKey<FormState> cardFormKey
  +bool showBackSide
  +AppConfigProvider? provider
  +TextEditingController nameController
  +TextEditingController addressController
  +TextEditingController phoneController
  +TextEditingController postalCodeController
  +TextEditingController nameOnCard
  +TextEditingController numberOnCard
  +TextEditingController cvvCode
  +TextEditingController expiryDate
  +OrderResponse orderResponse
  +void onBackPress()
  +double calcTotal()
  +String? nameValidation()
  +String? addressValidation()
  +String? phoneValidation()
  +String? postalCodeValidation()
  +void onContinueToPaymentPress()
  +String? cardValidation()
  +void onCompletePaymentPress()
  +void changeCardData()
}

"ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel" o-- "ecommerce::Domain::UseCase::PlaceOrderUseCase.dart::PlaceOrderUseCase"
"ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel" o-- "ecommerce::Presentation::UI::Payment::PaymentNavigator.dart::PaymentNavigator"
"ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel" o-- "ecommerce::Core::Provider::AppConfigProvider.dart::AppConfigProvider"
"ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel" o-- "ecommerce::Domain::Models::Order::OrderResponse.dart::OrderResponse"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::Payment::PaymentViewModel.dart::PaymentViewModel"

class "ecommerce::Presentation::UI::Payment::Tabs::CridetCardTab.dart::CreditCardTab" {
  +State<CreditCardTab> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Payment::Tabs::CridetCardTab.dart::CreditCardTab"

class "ecommerce::Presentation::UI::Payment::Tabs::CridetCardTab.dart::_CreditCardTabState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Payment::Tabs::CridetCardTab.dart::_CreditCardTabState"

class "ecommerce::Presentation::UI::Payment::Tabs::ReceiptTab.dart::ReceiptTab" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Payment::Tabs::ReceiptTab.dart::ReceiptTab"

class "ecommerce::Presentation::UI::Payment::Tabs::UserInfoTab.dart::UserInfoTab" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Payment::Tabs::UserInfoTab.dart::UserInfoTab"

class "ecommerce::Presentation::UI::Payment::Widgets::MyTextField.dart::MyTextField" {
  +String hintText
  +TextEditingController controller
  +IconData prefix
  +TextInputType keyboard
  +Function validation
  +Widget build()
}

"ecommerce::Presentation::UI::Payment::Widgets::MyTextField.dart::MyTextField" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"ecommerce::Presentation::UI::Payment::Widgets::MyTextField.dart::MyTextField" o-- "flutter::src::widgets::icon_data.dart::IconData"
"ecommerce::Presentation::UI::Payment::Widgets::MyTextField.dart::MyTextField" o-- "flutter::src::services::text_input.dart::TextInputType"
"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::Payment::Widgets::MyTextField.dart::MyTextField"

abstract class "ecommerce::Presentation::UI::PickImage::PickImageScreenNavidator.dart::PickImageScreenNavigator" {
  +dynamic showErrorMessage()
  +dynamic showSuccessMessage()
  +dynamic showLoading()
  +dynamic goToHomeScreen()
  +dynamic hideDialog()
}

class "ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::PickImageScreen" {
  {static} +String routeName
  +State<PickImageScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::PickImageScreen"

class "ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::_PickImageScreenState" {
  +ImagePicker picker
  +XFile? images
  +File? image
  +PickImageScreenViewModel viewModel
  +void initState()
  +void dispose()
  +Widget build()
  +dynamic showErrorMessage()
  +dynamic hideDialog()
  +dynamic showLoading()
  +dynamic showSuccessMessage()
  +dynamic goToHomeScreen()
}

"ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::_PickImageScreenState" o-- "image_picker::image_picker.dart::ImagePicker"
"ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::_PickImageScreenState" o-- "cross_file::src::types::interface.dart::XFile"
"ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::_PickImageScreenState" o-- "dart::io::File"
"ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::_PickImageScreenState" o-- "ecommerce::Presentation::UI::PickImage::PickImageScreenViewModel.dart::PickImageScreenViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::_PickImageScreenState"
"ecommerce::Presentation::UI::PickImage::PickImageScreenNavidator.dart::PickImageScreenNavigator" <|-- "ecommerce::Presentation::UI::PickImage::PickImageScreenView.dart::_PickImageScreenState"

class "ecommerce::Presentation::UI::PickImage::PickImageScreenViewModel.dart::PickImageScreenViewModel" {
  +AuthUploadUserImageUseCase useCase
  +PickImageScreenNavigator? navigator
  +void uploadImage()
  +void goToHomeScreen()
}

"ecommerce::Presentation::UI::PickImage::PickImageScreenViewModel.dart::PickImageScreenViewModel" o-- "ecommerce::Domain::UseCase::AuthUploadUserImageUseCase.dart::AuthUploadUserImageUseCase"
"ecommerce::Presentation::UI::PickImage::PickImageScreenViewModel.dart::PickImageScreenViewModel" o-- "ecommerce::Presentation::UI::PickImage::PickImageScreenNavidator.dart::PickImageScreenNavigator"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::PickImage::PickImageScreenViewModel.dart::PickImageScreenViewModel"

abstract class "ecommerce::Presentation::UI::ProductDetails::ProductDetailsNavigator.dart::ProductDetailsNavigator" {
  +void showLoading()
  +void hideDialog()
  +void showSuccessMessage()
}

class "ecommerce::Presentation::UI::ProductDetails::ProductDetailsView.dart::ProductDetailsScreen" {
  {static} +String routeName
  +State<ProductDetailsScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::ProductDetailsView.dart::ProductDetailsScreen"

class "ecommerce::Presentation::UI::ProductDetails::ProductDetailsView.dart::_ProductDetailsScreenState" {
  +ProductDetailsViewModel viewModel
  +void initState()
  +void dispose()
  +Widget build()
  +void hideDialog()
  +void showLoading()
  +void showSuccessMessage()
}

"ecommerce::Presentation::UI::ProductDetails::ProductDetailsView.dart::_ProductDetailsScreenState" o-- "ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::ProductDetails::ProductDetailsView.dart::_ProductDetailsScreenState"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsNavigator.dart::ProductDetailsNavigator" <|-- "ecommerce::Presentation::UI::ProductDetails::ProductDetailsView.dart::_ProductDetailsScreenState"

class "ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" {
  +GetProductDetailsUseCase getProductDetailsUseCase
  +AddToWishListUseCase addToWishListUseCase
  +DeleteFromWishListUseCase deleteFromWishListUseCase
  +AddProductToCartUseCase addProductTOCartUseCase
  +ProductDetails? product
  +String? errorMessage
  +AppConfigProvider? provider
  +String? id
  +Product? abstractProduct
  +String image
  +ProductDetailsNavigator? navigator
  +void getProductDetails()
  +void onTryAgainPress()
  +void onImagePress()
  +void onAddToCartPress()
}

"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Domain::UseCase::GetProductDetailsUseCase.dart::GetProductDetailsUseCase"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Domain::UseCase::AddToWishListUseCase.dart::AddToWishListUseCase"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Domain::UseCase::DeleteFromWishListUseCase.dart::DeleteFromWishListUseCase"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Domain::UseCase::AddProductToCartUseCase.dart::AddProductToCartUseCase"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Domain::Models::Products::ProductDetails.dart::ProductDetails"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Core::Provider::AppConfigProvider.dart::AppConfigProvider"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Domain::Models::Products::Prdouct.dart::Product"
"ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel" o-- "ecommerce::Presentation::UI::ProductDetails::ProductDetailsNavigator.dart::ProductDetailsNavigator"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::ProductDetails::ProductDetailsViewModel.dart::ProductDetailsViewModel"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::BrandAndRatingWidget.dart::BrandAndRatingWidget" {
  +String brand
  +String rating
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::BrandAndRatingWidget.dart::BrandAndRatingWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::ButtonsWidget.dart::ButtonsWidget" {
  +Function onAddToCartPress
  +State<ButtonsWidget> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::ButtonsWidget.dart::ButtonsWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::ButtonsWidget.dart::_ButtonsWidgetState" {
  +Widget build()
}

"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::ButtonsWidget.dart::_ButtonsWidgetState"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::DescriptionImageWidget.dart::DescriptionImageWidget" {
  +String image
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::DescriptionImageWidget.dart::DescriptionImageWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::DescriptionWIdget.dart::DescriptionWidget" {
  +String desctiption
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::DescriptionWIdget.dart::DescriptionWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::FeedBacksWidget.dart::FeedBacksWidget" {
  +double rating
  +List<FeedBack>? feedbacks
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::FeedBacksWidget.dart::FeedBacksWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::ImagesListWidget.dart::ImagesListWidget" {
  +List<String> images
  +Function onImagePress
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::ImagesListWidget.dart::ImagesListWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::ImageWidget.dart::ImageWidget" {
  +String image
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::ImageWidget.dart::ImageWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::NameWidget.dart::NameWidget" {
  +String name
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::NameWidget.dart::NameWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::PriceWidget.dart::PriceWidget" {
  +String price
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::PriceWidget.dart::PriceWidget"

class "ecommerce::Presentation::UI::ProductDetails::Widgets::UserRatingWidget.dart::UserRatingWidget" {
  +String? rating
  +Widget build()
}

"flutter::src::widgets::framework.dart::StatelessWidget" <|-- "ecommerce::Presentation::UI::ProductDetails::Widgets::UserRatingWidget.dart::UserRatingWidget"

abstract class "ecommerce::Presentation::UI::ProductsList::ProductsListNavigator.dart::ProductsListNavigator" {
  +void goToProductDetailsScreen()
  +void showLoading()
  +void hideDialog()
  +void showSuccessMessage()
}

class "ecommerce::Presentation::UI::ProductsList::ProductsListView.dart::ProductsListScreen" {
  {static} +String routeName
  +State<ProductsListScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::ProductsList::ProductsListView.dart::ProductsListScreen"

class "ecommerce::Presentation::UI::ProductsList::ProductsListView.dart::_ProductsListScreenState" {
  +ProductsListViewModel viewModel
  +void initState()
  +void dispose()
  +Widget build()
  +void goToProductDetailsScreen()
  +void hideDialog()
  +void showLoading()
  +void showSuccessMessage()
}

"ecommerce::Presentation::UI::ProductsList::ProductsListView.dart::_ProductsListScreenState" o-- "ecommerce::Presentation::UI::ProductsList::ProductsListViewModel.dart::ProductsListViewModel"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::ProductsList::ProductsListView.dart::_ProductsListScreenState"
"ecommerce::Presentation::UI::ProductsList::ProductsListNavigator.dart::ProductsListNavigator" <|-- "ecommerce::Presentation::UI::ProductsList::ProductsListView.dart::_ProductsListScreenState"

class "ecommerce::Presentation::UI::ProductsList::ProductsListViewModel.dart::ProductsListViewModel" {
  +GetProductsByCategoryIdUseCase getProductsByCategoryIdUseCase
  +AddToWishListUseCase addToWishListUseCase
  +DeleteFromWishListUseCase deleteFromWishListUseCase
  +ProductsListNavigator? navigator
  +String? errorMessage
  +List<Product>? products
  +double categoryId
  +void getProductsByCategoryId()
  +void onTryAgainButtonPress()
  +void onWidgetPress()
  +void onFavoritePress()
}

"ecommerce::Presentation::UI::ProductsList::ProductsListViewModel.dart::ProductsListViewModel" o-- "ecommerce::Domain::UseCase::GetProductsByCategoryIdUseCase.dart::GetProductsByCategoryIdUseCase"
"ecommerce::Presentation::UI::ProductsList::ProductsListViewModel.dart::ProductsListViewModel" o-- "ecommerce::Domain::UseCase::AddToWishListUseCase.dart::AddToWishListUseCase"
"ecommerce::Presentation::UI::ProductsList::ProductsListViewModel.dart::ProductsListViewModel" o-- "ecommerce::Domain::UseCase::DeleteFromWishListUseCase.dart::DeleteFromWishListUseCase"
"ecommerce::Presentation::UI::ProductsList::ProductsListViewModel.dart::ProductsListViewModel" o-- "ecommerce::Presentation::UI::ProductsList::ProductsListNavigator.dart::ProductsListNavigator"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::ProductsList::ProductsListViewModel.dart::ProductsListViewModel"

abstract class "ecommerce::Presentation::UI::Registration::RegistrationScreenNavigator.dart::RegistrationScreenNavigator" {
  +dynamic showErrorMessage()
  +dynamic showSuccessMessage()
  +dynamic showLoading()
  +dynamic goToPickImageScreen()
  +dynamic updateToken()
  +dynamic hideDialog()
}

class "ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::RegistrationScreen" {
  {static} +String routeName
  +State<RegistrationScreen> createState()
}

"flutter::src::widgets::framework.dart::StatefulWidget" <|-- "ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::RegistrationScreen"

class "ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::_RegistrationScreenState" {
  +bool isVisible
  +RegistrationScreenViewModel viewModel
  +DateTime date
  +GlobalKey<FormState> formKey
  +TextEditingController nameController
  +TextEditingController emailController
  +TextEditingController passwordController
  +TextEditingController rePasswordController
  +TextEditingController phoneController
  +void initState()
  +void dispose()
  +Widget build()
  +void showMyDatePicker()
  +Widget dataFormField()
  +Widget passwordFormField()
  +void register()
  +dynamic showErrorMessage()
  +dynamic hideDialog()
  +dynamic showLoading()
  +dynamic showSuccessMessage()
  +dynamic updateToken()
  +dynamic goToPickImageScreen()
}

"ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::_RegistrationScreenState" o-- "ecommerce::Presentation::UI::Registration::RegistrationScreenViewModel.dart::RegistrationScreenViewModel"
"ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::_RegistrationScreenState" o-- "flutter::src::widgets::framework.dart::GlobalKey<FormState>"
"ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::_RegistrationScreenState" o-- "flutter::src::widgets::editable_text.dart::TextEditingController"
"flutter::src::widgets::framework.dart::State" <|-- "ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::_RegistrationScreenState"
"ecommerce::Presentation::UI::Registration::RegistrationScreenNavigator.dart::RegistrationScreenNavigator" <|-- "ecommerce::Presentation::UI::Registration::RegistrationScreenView.dart::_RegistrationScreenState"

class "ecommerce::Presentation::UI::Registration::RegistrationScreenViewModel.dart::RegistrationScreenViewModel" {
  +RegistrationScreenNavigator? navigator
  +AuthRegistrationUseCase useCase
  +String? nameValidation()
  +String? phoneValidation()
  +void register()
  +void goToHome()
}

"ecommerce::Presentation::UI::Registration::RegistrationScreenViewModel.dart::RegistrationScreenViewModel" o-- "ecommerce::Presentation::UI::Registration::RegistrationScreenNavigator.dart::RegistrationScreenNavigator"
"ecommerce::Presentation::UI::Registration::RegistrationScreenViewModel.dart::RegistrationScreenViewModel" o-- "ecommerce::Domain::UseCase::AuthRegistrationUseCase.dart::AuthRegistrationUseCase"
"flutter::src::foundation::change_notifier.dart::ChangeNotifier" <|-- "ecommerce::Presentation::UI::Registration::RegistrationScreenViewModel.dart::RegistrationScreenViewModel"


@enduml
